language: go

env:
  - GO111MODULE=on

go:
  - "1.16.x"
  - tip

matrix:
  allow_failures:
    - go: tip

script:
  - go mod vendor
  - go test -mod vendor -race -cover -coverprofile=coverage.txt -covermode=atomic -timeout=2m ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
